### ISSUE TITLE
Issue in Azure DevOps after last update

### ISSUE THREAD

**Issue by esabkov** [mohitbagra/azure-devops-extensions#5] opened 2019-06-13 09:00 UTC
When we open a Product Backlog Item or Work Item from the backlog, the checklist section keeps loading. Eventually the page is broken.
![1](https://user-images.githubusercontent.com/51781268/59419101-e1a75800-8dd2-11e9-8049-7b9b8130e989.png)

**Comment by GregTrevellick** [comment] 2019-06-13 11:20
I get the same issue today, just since the recent update

**Comment by FransVanEk** [comment] 2019-06-13 11:33
same here

**Comment by GregTrevellick** [comment] 2019-06-13 12:02
Disabling the extension temporarily cures the issue, but I'm told the "Definition of Done" extension (not in github unfortunately) has same or similar issue.

**Comment by ghamblin1** [comment] 2019-06-13 19:04
Same here.  A lot of hangs, and "visualstudio.com is not responding due to a long-running script."   Unusable right now.

**Comment by M0053-UK** [comment] 2019-06-14 05:47
**Had to disable the extension following the 3.2.2 update.** 😢
As others describe; a never ending hang for some users (Might be related to elevated project privileges, as basic users can continue use)

**Comment by M0053-UK** [comment] 2019-06-14 05:51
> **Had to disable the extension following the 3.2.2 update.** 😢
> As others describe; a never ending hang for some users (Might be related to elevated project privileges, as basic users can continue use)

**Just noticed this on the Extension's [review section](https://marketplace.visualstudio.com/items?itemName=mohitbagra.workitem-checklist&ssr=false#review-details) (Hopefully we get a fix soon)**
Mohit Bagra
_17 hours ago_
I did some investigation and it looks like an issue in Azure Devops product, not my extension. I am working with Azure Devops team to get this issue fixed soon.

**Comment by eucanete** [comment] 2019-06-14 06:51
Hi guys,  I am experiencing the same issue. 
I cant view, add, edit the work items (userstory, bugs, features, tasks)

When I disabled the Extension, everything is working fine again.

**Comment by mohitbagra** [comment] 2019-06-14 11:58
Sorry for the trouble. But I have found that this happens due to a bug in Azure Devops service, its not a bug in the extension. It only happens when you open a work item from backlog or sprints page. I am working with Azure Devops team to get this fixed. ETA is early next week. Till then, please disable the extension. I have done some major refactoring in the extension, so re-publishing an older version of the extension is sadly not possible as that may cause other issues.

**Comment by wpschaub** [comment] 2019-06-17 19:00
@mohitbagra any update on this issue? We had to disable your extension in our organization and are poised for the fix. Could you elaborate on "bug in Azure DevOps service"?

**Comment by mohitbagra** [comment] 2019-06-17 19:03
The fix has been made in Azure Devops. Its just the matter of when the fix gets deployed to your account. It should get deployed by tomorrow or day after at max.
There was an issue in the way an extension communicates with the host page in Azure Devo

**Comment by wpschaub** [comment] 2019-06-17 19:06
Thank you for the quick update! Hope the Azure DevOps fix will be rolled out soon :)

**Comment by M0053-UK** [comment] 2019-06-18 09:05
> The fix has been made in Azure Devops. Its just the matter of when the fix gets deployed to your account. It should get deployed by tomorrow or day after at max.
> There was an issue in the way an extension communicates with the host page in Azure Devops. It was not something an extension can fix. The fix needed to made on Azure Devops

Could you link us to the underlying Azure DevOps bug ticket please?
[https://developercommunity.visualstudio.com/spaces/21/index.html](https://developercommunity.visualstudio.com/spaces/21/index.html)

**Comment by AndreasSoehnleinKloon** [comment] 2019-06-19 08:48
There is a issue open here https://developercommunity.visualstudio.com/content/problem/606343/browser-crash-when-viewedit-work-item-due-to-check.html

**Comment by xzlichao** [comment] 2019-06-21 07:41
@mohitbagra May I know when will the fix be deployed to our accounts? Do we have a plan or timeline?

**Comment by mohitbagra** [comment] 2019-06-21 17:02
The deployment was supposed to finish this week but due to some unexpected issues, it got delayed. It should be deployed in all account by EOD Monday.

**Comment by mohitbagra** [comment] 2019-06-21 17:04
Unfortunately no fix can be made on the extension to resolve this issue. I made some data shape changes in my new update so rolling back the extension to a previous "working" version would actually start causing worse compat issues. I sincerely apologize for causing this inconvenience and I'll definitely try my best to not cause any such issues in future. 

I'll post an update in this thread as soon as the deployment finishes.

**Comment by mohitbagra** [comment] 2019-06-21 22:14
Update: The fix has been deployed. It should be available on all accounts now. Users can now enable the extension.

**Closed** 2019-06-23 23:55 UTC
